debug: true
uuid: 3d54aaf6-aa9a-489b-8806-be07643ecd76
token_id: vjBinO0oldltdzL6
token: CXbDk5xRp1jCqbRYZqQjVeLtWMAbh0pWK5SouBGJRakpOkpseMpqQm3fiOqn5VxU
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/localhost/fullchain.pem
    key: /etc/letsencrypt/live/localhost/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://localhost'